"""Add project models and role

Revision ID: 8f607cf0f40a
Revises: 23487874438b
Create Date: 2026-09-01 05:25:49.383719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f607cf0f40a'
down_revision: Union[str, Sequence[str], None] = '23487874438b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_members', sa.Column('role', sa.Enum('ADMIN', 'PROJECT_LEAD', 'SENIOR_DEVELOPER', 'DEVELOPER', name='roleenum'), nullable=False))
    op.add_column('project_members', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('project_members', 'created_at')
    project_status_enum = postgresql.ENUM('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatusenum')
    project_status_enum.create(op.get_bind())
    
    op.add_column('projects', sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatusenum'), nullable=False, server_default='ACTIVE'))
    op.add_column('projects', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.drop_column('projects', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'status')
    op.add_column('project_members', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('project_members', 'joined_at')
    op.drop_column('project_members', 'role')
    op.drop_table('project_activity')
    # ### end Alembic commands ###
