"""sla_engine

Revision ID: 928a83f027ce
Revises: 26c8e1588a73
Create Date: 2026-09-01 14:37:08.003699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '928a83f027ce'
down_revision: Union[str, Sequence[str], None] = '26c8e1588a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriorityenum', create_type=False), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=False),
    sa.Column('at_risk_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_policies_active'), 'sla_policies', ['active'], unique=False)
    op.create_index(op.f('ix_sla_policies_priority'), 'sla_policies', ['priority'], unique=False)
    op.create_table('ticket_slas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('response_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ON_TRACK', 'AT_RISK', 'BREACHED', 'PAUSED', 'COMPLETED', name='slastatusenum'), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pause_seconds', sa.Integer(), nullable=False),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['sla_policies.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_slas_ticket_id'), 'ticket_slas', ['ticket_id'], unique=True)
    op.drop_column('tickets', 'sla_started_at')
    op.drop_column('tickets', 'sla_due_at')
    op.drop_column('tickets', 'sla_policy_id')
    op.drop_column('tickets', 'sla_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sla_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('sla_policy_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('sla_due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tickets', sa.Column('sla_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ticket_slas_ticket_id'), table_name='ticket_slas')
    op.drop_table('ticket_slas')
    op.drop_index(op.f('ix_sla_policies_priority'), table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_active'), table_name='sla_policies')
    op.drop_table('sla_policies')
    # ### end Alembic commands ###
