"""replace_is_active_with_status_and_pin

Revision ID: a49ce61646f3
Revises: 8f607cf0f40a
Create Date: 2026-09-01 07:01:27.424537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49ce61646f3'
down_revision: Union[str, Sequence[str], None] = '8f607cf0f40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userstatusenum = sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', name='userstatusenum')
    userstatusenum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('status', userstatusenum, server_default='ACTIVE', nullable=False))
    op.add_column('users', sa.Column('activation_pin', sa.String(length=10), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'activation_pin')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
